name: setlistherofl
description: Setlist Hero

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  get_it: ^4.0.2
  flutter_web_auth: ^0.2.4
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: 4.0.5345
  sheet_music: ^0.3.0
  jsonml: ^0.1.8+1
  tokenizer: ^0.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700